### ISSUE TITLE
Remove links to functions in the code block

### ISSUE THREAD

**Issue by henrywangnl** [maelle/goodpress#16]
Hi Maelle,

It's me again :-)

I'm comparing the CSS styles between Rmd output with my WordPress theme. One thing I notice that links to R functions in the code block are automated generated. For example, in the post of https://rmd-wordpress.eu/post-rmd/, there is a link to summary() function (link to https://rdrr.io/r/base/summary.html).

Is it possible to remove it if I want?

Thanks!

**Comment by maelle** [comment]
ah, good question, that'd be something to change on downlit/hugodown side of things https://github.com/r-lib/downlit/

**Comment by henrywangnl** [comment]
Never mind, I removed the text underline via CSS...

**Comment by maelle** [comment]
Ok!

I had a question for you, did you use FTP or a plugin to edit .htaccess? Had you ever touched that file before?

**Comment by henrywangnl** [comment]
I used a plugin called `WP Htaccess Editor`

**Comment by maelle** [comment]
Hehe that is what I did too on the test website. Thanks.
