### ISSUE TITLE
Open blog url automatically

### ISSUE THREAD

**Issue by henrywangnl** [maelle/goodpress#19]
I like that it automatically opens the post URL on the browser after `wp_post` is called successfully, but it seems not every time.

**Comment by maelle** [comment]
ah weird :thinking: it should always happen when the post is published / private

https://github.com/maelle/goodpress/blob/5a14966e93a1b7abf539a4267bfc75e2b3a05606/R/post.R#L192-L195

**Comment by henrywangnl** [comment]
it didn't replicate anymore, never mind!
