### ISSUE TITLE
Images didn't show

### ISSUE THREAD

**Issue by henrywangnl** [maelle/goodpress#22]
for example, one image links to this path: [https://henrywang.nl/rmarkdown-wordpress-goodpress/figs/wp.png](https://henrywang.nl/rmarkdown-wordpress-goodpress/figs/wp.png)

**Comment by maelle** [comment]
is the source of your post public? it'd help me to see index.Rmd and index.md.

**Comment by maelle** [comment]
This is how I included an external image in an example post

https://github.com/maelle/goodpress/blob/5a14966e93a1b7abf539a4267bfc75e2b3a05606/inst/post-example/index.Rmd#L48-L50

**Comment by henrywangnl** [comment]
here you go:
https://github.com/henrywangnl/Blog/blob/master/20200625/index.Rmd

**Comment by maelle** [comment]
thanks, I made a suggestion there.

**Comment by maelle** [comment]
to be clear, I need to make the Xpat query less strict, but I like the idea that there's a bug when there's no alternative text :stuck_out_tongue_winking_eye:

**Comment by henrywangnl** [comment]
hmmm, it didn't seem change: https://henrywang.nl/rmarkdown-wordpress-goodpress/

**Comment by maelle** [comment]
I'll look into it shortly

**Comment by maelle** [comment]
I knitted Rmd and got the image https://rmd-wordpress.eu/rmarkdown-wordpress-goodpress/ (don't worry I'll remove your post from my website ;-) )

I'll know try without alt text.

**Comment by maelle** [comment]
even without alt text I get the image https://rmd-wordpress.eu/rmarkdown-wordpress-goodpress/, weird.

it's especially weird to me that it works for the other plot in your post on your blog!

**Comment by maelle** [comment]
Can you please look in your WordPress gallery (from the dasbhoard) to see whether wp.png is there?

**Comment by henrywangnl** [comment]
> Can you please look in your WordPress gallery (from the dasbhoard) to see whether wp.png is there?

yes, it's there lol

**Comment by maelle** [comment]
as wp.png, right, not the old name?

at least it got uploaded, the bug must be after that

**Comment by henrywangnl** [comment]
yes, it's `wp.png`: https://henrywang.nl/wp-content/uploads/2020/06/wp.png

**Comment by maelle** [comment]
weird, I'm still thinking about what can have gone wrong. btw can you update goodpress, and re-run wp_post()?

**Comment by henrywangnl** [comment]
I re-install it but it didn't work.

**Comment by henrywangnl** [comment]
I tried to upload a new image and it works now...

**Comment by maelle** [comment]
but the ggplot2 plot disappeared?

**Comment by henrywangnl** [comment]
yes, ggplot2 plots work

**Comment by henrywangnl** [comment]
oh no, even ggplot2 plots don't show anymore haha

**Comment by henrywangnl** [comment]
I think something is wrong with the file path handler, which works weird...

**Comment by maelle** [comment]
So locally you still have the plots in the figs folder but they don't get uploaded to the gallery?

**Comment by henrywangnl** [comment]
> So locally you still have the plots in the figs folder but they don't get uploaded to the gallery?

Yes, the plots are still there. I'm not sure if they are uploaded to WP every time I call `wp_post` but I can see they are in galley.

**Comment by maelle** [comment]
how about you delete them from the gallery manually and rerun the function?

**Comment by henrywangnl** [comment]
haha let me try

**Comment by henrywangnl** [comment]
they are uploaded to gallery successfully but didn't show correctly in the post.

**Comment by maelle** [comment]
mmmh can you replace `post_folder` with the correct path and run

```r

post_folder <- "inst/post-example3"
file.create(file.path(post_folder, "index.html"))
withr::with_dir(
  post_folder,
  rmarkdown::pandoc_convert(
    "index.md",
    to = "html",
    output = "index.html",
    wd = getwd(),
    options = "--mathjax"
  )
)
content <- xml2::read_html(file.path(post_folder, "index.html"))
imgs <- xml2::xml_find_all(content, "//img")
imgs

```

this is to check the XPat query.

**Comment by henrywangnl** [comment]
here is what I get:

```
{xml_nodeset (2)}
[1] <img src="figs/unnamed-chunk-3-1.png" width="700px" style="display: block; margin: auto;">
[2] <img src="figs/wp.png" width="700px" style="display: block; margin: auto;">
```

**Comment by maelle** [comment]
Argh so the Xpat query works. I'm sorry, I'm a bit puzzled.

I think what I'd try is

* re-install goodpress
* delete post from WordPress dashboard
* delete .wordpress.yml
* delete the plots that were generated, from figs
* delete index.md
* reknit index.Rmd
* rerun wp_post()

**Comment by maelle** [comment]
(yeah sorry that's what you get for being an early tester/adopter of the package: all the problems)

**Comment by henrywangnl** [comment]
No worries! I did learn a lot from the discussion!

**Comment by henrywangnl** [comment]
> I think what I'd try is

As you see from my blog, the steps you suggest work now!
Yet I have no idea what happened haha!

**Comment by maelle** [comment]
argh yeah sometimes one needs to resort to some version of "let's try turning it off an on again" or "delete everything and starts again" :sweat_smile: I'm very relieved it worked!!

**Comment by maelle** [comment]
I don't see what we can add to the docs so I'll close this. :-)

**Comment by henrywangnl** [comment]
Hi Maelle,

It seems that this issue appears again even I tried the steps you suggested last time.
Could you please check it for me?
My post: https://henrywang.nl/roc-curve-simulation-classification-performance/
Post source: https://github.com/henrywangnl/Blog/tree/master/20200714
Thanks!

**Comment by henrywangnl** [comment]
I fixed it by changing the image URLs on the WordPress Dashboard for the time being, so now the post looks fine...

**Comment by maelle** [comment]
Argh, sorry I don't have time to dive into this at the moment (which is also why I took so long to respond).

I see there are `.DS_store` files that aren't needed, but I don't think they can be the bug source (worth trying to delete them and then adding `.DS_store` to `.gitignore`).

**Comment by maelle** [comment]
It's of course especially problematic since adding the images via the dashboard sounds painful!

If you feel like having a look yourself see

https://github.com/maelle/goodpress/blob/d53850cf194fe94a831e4070c4866f0dae923b8e/R/post.R#L142-L160

and 

https://github.com/maelle/goodpress/blob/d53850cf194fe94a831e4070c4866f0dae923b8e/R/post.R#L219-L245

**Comment by maelle** [comment]
what's also important to investigate is

* are the images uploaded to WordPress?

* or is the problem "only" that their URL isn't changed in the content that's sent to the API?

**Comment by maelle** [comment]
A last wild guess for today, apart from deleting `.DS_store` can you also try _not_ using underscores in filenames? Who knows. Sorry for not being more helpful.

**Comment by henrywangnl** [comment]
Regarding this issue, the images not shown properly are those generated by r chunk codes as the images urls in the post are linked to the folder of `figs` not to the wordpress dashboard url.

**Comment by henrywangnl** [comment]
Hi @maelle 

I think this issue might because of the following code but I didn't verify it yet, so just to give you an idea:
As `media` is a data frame with two columns, `length(media)` and `seq_along(media)` may not what you want here. They will only loop the first two images. I guess you mean `!is.null()` or `nrow()` or something.

https://github.com/maelle/goodpress/blob/d53850cf194fe94a831e4070c4866f0dae923b8e/R/post.R#L151-L162

**Comment by maelle** [comment]
Would you want to try & make a PR?

**Comment by henrywangnl** [comment]
Sure Maelle!
I'll try it.

Thanks
Henry
