### ISSUE TITLE
how to support both APIs

### ISSUE THREAD

**Issue by maelle** [maelle/goodpress#24]
@hrbrmstr :wave:

* depend on pressur by @hrbrmstr or use its auth function or? In pressur there are more functions. some of the functionality like `wp_about_me()` cannot be mirrored with the wordpress dot org API.

* how to best document the adventure to follow (super important to make that user-friendly and clear)

    * an user needs to choose an API based on their website.
    * an user should add custom CSS for syntax highlighting but you can't do that for a free/cheap wordpress dot com website.
    * an user should add custom JS for MathJax (not all users need that) but you can't do that for a free/cheap wordpress dot com website.

**Comment by maelle** [comment]
from https://twitter.com/hrbrmstr/status/1276863122440151042

free/cheap http://wordpress.com def has .com API support. (I've just confirmed that for my own test wordpress dot com site)
havne't ever paid for http://wordpress.com so can't speak to biz
self-hosted w/o JetPack => .org api
self-hosted w/JetPack => .com API

**Comment by mdingemanse** [comment]
I think this one's also resolved by the changes on the WordPress side reflected in #39
