### ISSUE TITLE
deprecation warning: coercion from integer to character deprecated in purrr

### ISSUE THREAD

**Issue by mdingemanse** [maelle/goodpress#34]
Blown away by this package — works beautifully out of the box with built-in authentication in Wordpress 6.2. 

Running `goodpress::wp_post()` currently generates a deprecation warning:

```
> goodpress::wp_post(today_post, wordpress_url)
Post posted with status draft
Warning message:
Automatic coercion from integer to character was deprecated in purrr 1.0.0.
ℹ Please use an explicit call to `as.character()` within `map_chr()` instead.
ℹ The deprecated feature was likely used in the goodpress package.
```

**Comment by maelle** [comment]
Would you be willing to make a PR? Thanks for catching this!

**Comment by mdingemanse** [comment]
Afraid I'm not deeply enough into `purrr` or the jungle that is automatic coercion to track this one down!
