### ISSUE TITLE
Stop pandoc_convert() from wrapping code

### ISSUE THREAD

**Issue by mdingemanse** [maelle/goodpress#36]
Looks like the `pandoc_convert()` step in `wp_post()` wraps code by adding newline characters which upon import in WordPress become `<br />`. Solution is to add `wrap=none` to the pandoc option call: `options = c("--mathjax","--wrap=none")`

**Comment by maelle** [comment]
For next time, good to know: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

You might enjoy this post once it's published: https://github.com/ropensci/roweb3/pull/531 :grin:
