### ISSUE TITLE
support other authentication plugins?

### ISSUE THREAD

**Issue by maelle** [maelle/goodpress#9]
I do not want this package to support basic authentication because WordPress docs themselves say it should only be used for development (and because it's easier I'm afraid some people might use it in production).

Other plugins mentioned in the docs

* [JWT Authentication for WP REST API](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/). It demands editing .htaccess _and_ another file https://www.wpbeginner.com/beginners-guide/how-to-edit-wp-config-php-file-in-wordpress/ so it definitely sounds more intricate for users. _"Since this file contains a lot of sensitive information, it is recommended that you don't mess with this file unless you have absolutely no other choice."_ It sounds quite scary to me.

* [WordPress REST API – OAuth 1.0a Server](https://wordpress.org/plugins/rest-api-oauth1/) Probably not a good idea since at the moment I see _"This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress."_.

**Comment by maelle** [comment]
Note that the README mentions creating a special user for using the package, with editor rights rather than admin rights. It makes the application password less powerful.

I can imagine it might be a problem for some users though: since it's a different author than some other posts, it might not appear on the author page that the user would like.

**Comment by mdingemanse** [comment]
This issue seems to have become obsolete? The plugin you originally used has folded into WordPress core and (to my amazement I must say) everything worked beautifully out of the box.

**Comment by maelle** [comment]
Does it mean the docs need to be updated?

**Comment by mdingemanse** [comment]
I think so, yes. On mobile, so not in position to do so, but since WP 5.6 there are application passwords that can be made and revoked by the user on a per-application basis: https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/

This is what I'm using, just following the instructions (i.e. putting in ~Renviron), and it just works — so no plugin needed.

**Comment by maelle** [comment]
Thanks! Would you be willing to make a PR?
